FROM golang:1.15
RUN go get -v github.com/malikbenkirane/fillpdf
WORKDIR /go/src/github.com/malikbenkirane/fillpdf
RUN CGO_ENABLED=0 GOOS=linux go build -a --installsuffix cgo -o app .

FROM iron/base
RUN apk update; apk add pdftk
WORKDIR /root
COPY --from=0 /go/src/github.com/malikbenkirane/fillpdf/app . 
CMD ["./app"]
